name: ci

on: push

jobs:
  test:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.14'
    - run: |
        go install ./...
        go test -v ./...
